### ISSUE TITLE
[Bug]: Moss doesn't cause the clinging effect on the blocks it's placed on

### ISSUE THREAD

**Issue by Reshy** [samedifferent/Verdure#12]
### Mod Version

verdure-1.18.2-1.1.1.jar

### Mod Loader

Forge

### Mod Loader Version

4.1.0

### What happened?

The clinging effect, like what snow has, no longer seems to be working for moss:
![2022-05-03_21 50 22](https://user-images.githubusercontent.com/2096384/166625540-ef0e0507-5d17-4179-b88a-e83fb13cd152.png)

### latest.log

None.

**Comment by samedifferent** [comment]
If you are referring to the texture hanging off the sides, that was removed intentionally because we were directly overriding the vanilla resource pack and some people did not like that, as it's impossible to disable.

**Comment by Reshy** [comment]
Oh, is there no way in the config to allow it?
