### ISSUE TITLE
[Bug]: Issues with world generation and other

### ISSUE THREAD

**Issue by TheInfine** [samedifferent/Verdure#2]
### Mod Version

1.0.4

### Mod Loader

Forge

### Mod Loader Version

39.0.79

### What happened?

Rocks and pebbles generate on leaves and ice. They can also be placed on blocks that they shouldn't be able to (e. g. leaves and cobwebs).

Also this:
![kuva](https://user-images.githubusercontent.com/98822450/155205343-eb2314c5-2a9b-466f-b6cc-a5278c8fa549.png)
(flowers generating in cold biomes and on ice)

And this:
![kuva](https://user-images.githubusercontent.com/98822450/155205737-69827c6d-652c-4701-8c24-41fa0ce87481.png)
(I didn't place it but it's also possible. The blocks and biome are from Project Vibrant Journeys)

Rocks can generate in the air (though they always barely touch the ground):
![kuva](https://user-images.githubusercontent.com/98822450/155207296-d71f6083-bcba-4f57-8047-168b93e0efd8.png)

Mushroom shelves can generate on village houses (idk if this is intentional):
![kuva](https://user-images.githubusercontent.com/98822450/155205178-1bf584f5-b5a4-439f-8cdb-ee6ec85862e0.png)

**Comment by TheInfine** [comment]
Unrelated, but could you make rocks and pebbles waterloggable?

**Comment by samedifferent** [comment]
Fixed in https://github.com/samedifferent/Verdure/commit/2be4a47f80c214a083be29514db5a9af0ab43920
