### ISSUE TITLE
[Bug]: Trees growing on Farmers Delight Rich Soil replace that soil! But only with other mods. 

### ISSUE THREAD

**Issue by xFirefalconx** [samedifferent/Verdure#24]
### Mod Version

1.1.3a

### Mod Loader

Forge

### Mod Loader Version

40.2.4

### What happened?

Ok this is a bit of a chunk. Prepare some time. 

I noticed a weird bug in my own Modpack a while ago and reported it to the FD dev. They added a Mixin that prevents their special soil called "Rich Soil" from being replaced by tree growth. 
However, for a reason I am desperately trying to deduct (I am near to a mental breakdown at this point), there are certain trees that work fine, while others... nope. nope. nope. I tried all I could to nail down the issue but after a point where UI mods were involved and I was down to 190 active mods and each mod I deactivated per hand and tried to run the game, the issue was not possible to track, but I could reproduce it if I just copied all those mods and ran the game on a new profile with cleansed configs and all settings back to the start, new world, all new, updated, all I could do on my own. I am still working on the list but I fear for my mental health to go down a hill if I continue on my own. So I changed approaches and went: Hey, actually, I only tested small and large Spruce trees, what about others? So I planted all modded and vanilla, mushroom and trees on this block called "Rich Soil" from Farmer's Delight and bonemeal'ed the heck out of them. Took me about 3 days until this point.

I made a list (which is only based on one of the kind and not all of the kind so feel free to test a bit further):
Biomes O Plenty: Dirt

Fruit Trees: Rooted Dirt
Cherry Blossom Grotto: Rooted Dirt
Chinjufu: Rooted Dirt
Croptopia: Rooted Dirt
Cultural Delights: Rooted Dirt
Quark: Rooted Dirt
SimpleMango: Rooted Dirt

Untamed Wilds: Cannot plant?!
Hererei: Doesn't grow?

Atmospheric: CORRECT BEHAVIOUR
BYG: CORRECT BEHAVIOUR
Natural Decor: CORRECT BEHAVIOUR

Vanilla:
Mushroom: CORRECT BEHAVIOUR
Azalea: Rooted Dirt
Dark Oak: Humus (Verdure) (lead?!)
Acacia: Rooted Dirt
Jungle: Rooted Dirt
Birch: Rooted Dirt
Oak: Rooted Dirt

The Humus then lead me here. Humus is fine and all , but it's not supposed to grow on Rich Soil, as that soil is a special snowflake that doesn't degenerate, also addressed by the 1.2.1 Update on Farmer's Delight. 

I don't know how you address this situation and whether it's this mod causing the exact overwrite, I already went to KubeJS in desperation and asked if they could add a new way to detect block conversion so I would add that to remove any unwanted from Rich Soil. I am THAT desperate. I need help and some people to look at the situation. It's too much for me. I am at you guys' mercy at this point. 

For more info, this is the issue I am following on my modpack itself, to see the magnitude of what I am trying to tackle 
https://github.com/xFirefalconx/Royal-Equines-Petrified-Magic/issues/23 - there is a list of mods included, screenshots, a list of mods involved in the bug (though not limited to, as I have to wait a good 10 min each time to run the game, it adds up after a while)
https://github.com/vectorwing/FarmersDelight/issues/544 Vectorwing was so kind to reopen the issue but without info this is bound to fail. 
Since I tested it about 20 times now and each time I turned off Verdure the issue was gone, I hope this is the place to turn to and I hope you know what causes this or can at least tell me where else I should plead for help to get this solved for good. I am okay if it takes time, but I want a fix for 1.18.2. Desperately. my modpack breaks if people can't speed up their crop growth and plant all they need, especially because crafting the Compost to achieve Rich Soil is time and resource expensive, especially in the beginning. 
Thank you in advance for the time. I have high hopes we can accomplish a solution. 

### latest.log

No latest.log available, but ask me to create one if it is necessary.

**Comment by Drigonis** [comment]
hello, I appreciate the large amount of information here - but if you're experiencing issues with Verdure, your best option is to uninstall the mod. The current version is no longer supported and a rework is in the works. Apologies for the large amount of things you've seemed to have done to get to this point, but that's your best option. The overhaul is a while away and isn't being actively worked on

**Comment by xFirefalconx** [comment]
Alright so I found this config option and it seems to work with the Rooted Soil. 
![grafik](https://github.com/samedifferent/Verdure/assets/106652912/99c71dd8-f023-41dd-81ec-739f5bc9e845)

I have a few questions regarding mod removal/the overhaul that you have planned but don't yet execute though. 
1. Will it be for 1.18.2, too? Or shall I not bother because it will be kicked in the ground? 
2. There are older worlds of mine and from debugging the mod already I saw that there are holes in the ground when disabling Verdure. Can that be fixed somehow or is it not possible to add even such a thing to repair impacted player worlds? As far as when I re-enable the mod, the blocks get restored. Is there anything I can do to ensure my upgrading players don't experience ugly holes in their worlds? 
3. Overhaul incompatible or compatible with the old one in means of block placements that have happened on the old version?

I'd appreciate if you could give me these information so I know what's best to do in this situation. 
Thank you also for your fast reply.

**Comment by Drigonis** [comment]
use blockswap, enable retro-gen, and swap our blocks with air or grass or whatever block is fitting. that should replace all the mod's blocks. you may have to keep verdure installed for this, so just explore areas that are important to replace the verdure blocks in there - you may see gaps in the world in other places, but it shouldn't matter as much considering it's not as though they're right next to your base
the overhaul will be for 1.19.2 and will generate completely different from the old version, worldgen will be much more appealing and unique with proper patches of plants rather than just a block copy and pasted a few times in an area

**Comment by xFirefalconx** [comment]
Alright, if there's ever a chance of a backport for 1.18.2 will release, just let me know, anytime. I'll happily add it to a modpack update then. For now, I just disabled all the world gen options so it looks like it's not installed but will retain its current blocks.
