### ISSUE TITLE
[Bug]: Rocks and pebbles aren't mineable faster by pickaxes

### ISSUE THREAD

**Issue by thelegitdolt** [samedifferent/Verdure#3]
### Mod Version

1.0.4

### Mod Loader

Forge

### Mod Loader Version

39.0.88

### What happened?

[Bug]: Rocks and pebbles aren't mineable faster by pickaxes

### latest.log

don't tihnk it matters

**Comment by samedifferent** [comment]
Fixed in https://github.com/samedifferent/Verdure/commit/ed2078b3cfdac1f2dfdcb115ec5244531d7582a0
