### ISSUE TITLE
[Request/Performance]: Configuration for ground clutter

### ISSUE THREAD

**Issue by Reshy** [samedifferent/Verdure#6]
### Mod Version

verdure-1.18.2-1.0.5.jar

### Mod Loader

Forge

### Mod Loader Version

4.1.0

### What happened?

Verdure seems to lack any form of configuration file to tweak the spawn rates of the various types of ground cover the system uses.  Mostly this is a request for performance reasons, as the more ground cover there is, the more of an impact on the client there is.

### latest.log

None

**Comment by samedifferent** [comment]
This has been completely coded already, I just don't have permission from Drig (the mod artist) to release it yet until some other features are completed.
