### ISSUE TITLE
[Bug]: Moss has z-fighting

### ISSUE THREAD

**Issue by WenXin20** [samedifferent/Verdure#7]
### Mod Version

`v1.0.5`

### Mod Loader

Forge

### Mod Loader Version

`v40.1.0`

### What happened?

Moss has z-fighting with the block below on some sides.

![2022-04-27_22 21 02](https://user-images.githubusercontent.com/12000593/165669933-1263d8dd-65c3-44ff-b7d8-f848794efa9e.png)

### latest.log

n/a

**Comment by samedifferent** [comment]
This was fixed a while ago but I do not yet have permission to release the update.

**Comment by WenXin20** [comment]
Ah, thanks
